### ISSUE TITLE
Test runner ?

### ISSUE THREAD

**Issue by stefaneg** [chrisharrington/react-todo#1]
There is no mention on how to run the tests in the project.

**Comment by noer180895** [comment]
yes i agree, on how to run the tests in the project?

**Comment by chrisharrington** [comment]
Open up the "runner.html" file under the tests subdirectory. It's a standard Jasmine SpecRunner.html file.

**Comment by stefaneg** [comment]
Interesting. Not the standard way of doing this, but works. No live-reload though.
