### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by grmpz** [chrisharrington/react-todo#2]
rowland:react-todo/ (master*) $ make build                                                                                                              [11:18:03]
rm -rf bower_components
rm -rf node_modules
rm -rf public
rm -rf dist
npm install
npm WARN package.json react-todo@1.0.0 No repository field.
npm WARN optional dep failed, continuing fsevents@0.3.6

> brunch@1.8.2 postinstall /home/rowland/projects/react-todo/node_modules/brunch
> node -e "require('fs').readdir('lib',function(e){e&&require('child_process').exec('npm run prepublish')})"

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! brunch@1.8.2 postinstall: `node -e "require('fs').readdir('lib',function(e){e&&require('child_process').exec('npm run prepublish')})"`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the brunch@1.8.2 postinstall script.
npm ERR! This is most likely a problem with the brunch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -e "require('fs').readdir('lib',function(e){e&&require('child_process').exec('npm run prepublish')})"
npm ERR! You can get their info via:
npm ERR!     npm owner ls brunch
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-24-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/rowland/projects/react-todo
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rowland/projects/react-todo/npm-debug.log
npm ERR! not ok code 0
makefile:10: recipe for target 'build' failed
make: **\* [build] Error 1

Is there minimum node version required?

**Comment by chrisharrington** [comment]
I honestly have no idea. I'd suggest Googling that warning.

**Comment by grmpz** [comment]
Installing nodejs-legacy fixed the build error.  Closing
