### ISSUE TITLE
What are the setup requirements to run make?

### ISSUE THREAD

**Issue by lonmiller** [chrisharrington/react-todo#3]
Installed bower, etc but I do not see a make command. Running Windows 7. bower install runs successful but I don't see any make commands.

**Comment by chrisharringtoncm** [comment]
You'll need to run "make build" and to build everything, and then "make start" to get the web server up and running. Do you have make installed?

**Comment by chrisharrington** [comment]
Do you have make installed? If so, "make build" and then "make start" will get you up and running.

**Comment by lonmiller** [comment]
Where do I obtain make? is that just a download of the standard make tool at https://www.gnu.org/software/make/? I thought it was a Bower package or something similar, I didn't know the standard make could be used to build Javascript projects.

**Comment by chrisharrington** [comment]
Pretty sure that's the one.
